### PR TITLE
Revert "Add GitHub CI build workflow"

### PR DESCRIPTION
**Pull request by makzpain**
Reverts yasm/yasm#179

### CODE REVIEW

**Comment by makzpain** [comment]
#181

**Comment by PeterJohnson** [comment]
I don’t see how this fixes 181, it just removes CI. Did you push the right commit to this PR?

**Review by makzpain — COMMENTED** [review]
ytyt

**Review by makzpain — COMMENTED** [review]
#181 #182

**Comment by makzpain** [comment]
#183 # #

**Pull request closed without merging**
