### PR TITLE
Added -Wno-segreg-in-64bit to allow suppressing the annoying 'segment…

### PR DESCRIPTION
**Pull request by bird2tori**
VirtualBox has been using yasm since we ported our product to 64-bit and been very happy with.  There is one annoyance though, the warnings about segment registers in our 64-bit world switcher code and 64-bit CPU emulation test cases.  We can see how the warning is useful to other developers, but we'd like a way of shutting it up because we get hundreds of them.

The attached patch (I hope the attachment makes it thru) extends yasm_warn_class with a  YASM_WARN_SEGREG_IN_64BIT value which  yasm_x86__parse_check_regtmod is changed to use.  The yasm, vsyasm, and tasm front ends translates the "segreg-in-64bit" warning name to YASM_WARN_SEGREG_IN_64BIT, so that we can use -Wno-segreg-in-64bit to disable the warning.

Would be delighted if the patch was applied to the git master.

Cheers,
 bird.

### CODE REVIEW

**Comment by PeterJohnson** [comment]
This adds the option to the command line, but the patch doesn't include the code that actually suppresses the warning where it's generated?

**Comment by bird2tori** [comment]
Sorry about dropping the updated warning message. :/  I've committed the necessary change now. 

Thanks for the swift reply!
- bird

**Comment by PeterJohnson** [comment]
Can you squash these into a single commit?  Thanks.

**Comment by bird2tori** [comment]
Commit c0dc9e5 (c0dc9e52ec11dc89f2fc32d0437fc7b20e5d1256) contains all the changes. I'm new to git and github, so I hope I got it halfway right.

Cheers,
 bird.

**Comment by PeterJohnson** [comment]
Merged as a squashed commit.

**Pull request closed without merging**
