### PR TITLE
Update Mach-O for newer macOS

### LINKED ISSUE #141: Allow including target system information in objects on macOS.
I'm using macOS 10.15 and Xcode 11.2.1 and building ffmpeg on macOS and then link it to my project targeting macOS 10.12. When linking the linker gives such warnings:
```
ld: warning: building for macOS, but linking in object file (/Users/preston/Telegram/Libraries/macos/ffmpeg/libswscale/libswscale.a(input.o)) built for free standing
```
For all object files that were built using YASM.

For C and C++ sources additional compiler options are passed to Apple Clang: "-mmacosx-version-min=10.12" and this removes such problems for object files built from C / C++ sources. I guess it puts something like this in the object file:
```
Load command 1
      cmd LC_VERSION_MIN_MACOSX
  cmdsize 16
  version 10.12
      sdk 10.15
```
and this information is read by the linker and it doesn't complain.

Is it possible to add a flag to pass on macOS to YASM so that it will write such section as well? Those warnings are noisy and it seems they can't be disabled.

Other compilers (Crystal, Go, D) have (or had) this problem as well, see: https://github.com/golang/go/issues/33214#issuecomment-541353859

### PR DESCRIPTION
**Pull request by PeterJohnson**
- Create a dummy .llvmasm section for bitcode
- Add [buildversion] directive for setting minos and sdk versions, e.g. `[buildversion minos="10.14" sdk="10.14"]`.  This defaults to 10.5 on x64 and 10.4 on x86.

Fixes #141.

### CODE REVIEW

**Comment by sezero** [comment]
>  This defaults to 10.7.

Does this refuse linkage if, e.g. I'm targeting 10.4 for x86 or 10.5 for x64 builds?

**Comment by PeterJohnson** [comment]
I don’t know.  If it’s better to default it lower, that’s an easy change.

**Comment by sezero** [comment]
No failures, but I did get linker warnings:
```
ld: warning: object file (d_draw.o) was built for newer macOS version (10.7) than being linked (10.4)
ld: warning: object file (d_draw16.o) was built for newer macOS version (10.7) than being linked (10.4)
ld: warning: object file (d_draw16t.o) was built for newer macOS version (10.7) than being linked (10.4)
ld: warning: object file (d_parta.o) was built for newer macOS version (10.7) than being linked (10.4)
ld: warning: object file (d_partb.o) was built for newer macOS version (10.7) than being linked (10.4)
ld: warning: object file (d_polysa4.o) was built for newer macOS version (10.7) than being linked (10.4)
ld: warning: object file (d_polysa3.o) was built for newer macOS version (10.7) than being linked (10.4)
ld: warning: object file (d_polysa.o) was built for newer macOS version (10.7) than being linked (10.4)
ld: warning: object file (d_polysa2.o) was built for newer macOS version (10.7) than being linked (10.4)
ld: warning: object file (d_scana.o) was built for newer macOS version (10.7) than being linked (10.4)
ld: warning: ld: warning: object file (d_spr8.o) was built for newer macOS version (10.7) than being linked (10.4)
[...]
```
No guarantees that the warning would change into an error some day..

**Comment by sezero** [comment]
FWIW, this was with ld64 version 609, running as a cross-toolchain on linux.

**Comment by sezero** [comment]
>  Do you have a recommended default?

I'd say 10.4 when targeting x86, and 10.5 when targeting x64

**Comment by PeterJohnson** [comment]
Done

**Comment by sezero** [comment]
> Done

Perfect from my poin of view

**Comment by berkus** [comment]
How does it correlate with [this patch](https://github.com/desktop-app/yasm/commit/e129811f26db5db8eaa89264b6894850d9c25a76)?

**Comment by john-preston** [comment]
@berkus I hope I'll be able to drop my workarounds with this being merged.

**Comment by berkus** [comment]
@john-preston cool!

**Pull request merged**
